# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sns-checkout-extension"
client_id = "f1f6b0a50658781dbaca46fd47e9858a"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "umesh-dev-store.myshopify.com"
